version: '3.3'
services:
  mysql:
    build:
      context: dgyar-mysql/
      labels:
        com.dgyar.description: "Data node"
        com.dgyar.department: "IT"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=dgyar
#      - MYSQL_USER=dgyar@pluf
#      - MYSQL_PASSWORD=dgyar
      - MYSQL_DATABASE=dgyar
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    networks:
      - dgyar
  pluf:
    build:
      context: dgyar/
      labels:
        com.dgyar.description: "Public webapp"
        com.dgyar.department: "IT"
    volumes:
      - /local/storage:/var/www/storage
    ports:
      - "80:80"
    networks:
      - dgyar
    depends_on:
      - mysql
networks:
  dgyar: