version: "3.3"
services:
  prerender:
    build:
      context: prerender/
    labels:
      com.dgyar.title: "Prerender system"
      com.dgyar.description: "Create and manages prerendered pabes"
      com.dgyar.department: "IT"
    environment:
      SERVER_DIR: /root
      CHROME_BIN: /usr/bin/chromium-browser
      CHROME_PATH: /usr/lib/chromium/
      PAGE_DONE_CHECK_INTERVAL: 500
      PAGE_LOAD_TIMEOUT: 20000
      WAIT_AFTER_LAST_REQUEST: 250
    networks:
      - viraweb
  dms:
    build:
      context: dms/
    labels:
      com.dgyar.title: "Domain management system"
      com.dgyar.description: "Create and manages certificates, domains, and dns"
      com.dgyar.department: "IT"
    networks:
      - viraweb
    volumes:
      - type: volume
        source: plufStorage-vol
        target: /var/www/storage
      - type: volume
        source: sites-enabled-vol
        target: /var/www/sites-enabled
  mysql:
    build:
      context: mysql/
    labels:
      com.dgyar.description: "Data node"
      com.dgyar.department: "IT"
    command: --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: plufdb
      MYSQL_USER: pluf
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    networks:
      - viraweb
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql-vol
        target: /var/lib/mysql
  pluf:
    build:
      context: pluf/
    labels:
      com.dgyar.description: "Public webapp interface"
      com.dgyar.department: "IT"
    volumes:
      - type: volume
        source: plufStorage-vol
        target: /var/www/storage
      - type: volume
        source: plufLetsencrypt-vol
        target: /var/www/logs
      - type: volume
        source: sites-enabled-vol
        target: /etc/apache2/sites-enabled
    ports:
      - "80:80"
    networks:
      - viraweb
    depends_on:
      - mysql
networks:
  viraweb:
  
volumes:
  mysql-vol:
  plufStorage-vol:
  plufLog-vol:
  plufLetsencrypt-vol: 
  sites-enabled-vol: 
